name: "EAS Inject Env Action"
description: "GitHub Action to inject environment variables into EAS configuration"
runs:
  using: "node20"
  main: "dist/index.js"
inputs:
  profile_name:
    description: "The profile to update (e.g., production, test)"
    required: true
  directory:
    description: 'The directory where to find eas.json'
    default: ''
  fail_on_empty:
    description: 'Fail if an env key is an empty string'
    default: 'false'
  sort_keys:
    description: 'Sort the keys alphabetically'
    default: 'false'
